// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:380

#ifndef _TAO_IDL_TIMES_H_
#define _TAO_IDL_TIMES_H_

#include /**/ "ace/pre.h"

#include "TimeC.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/Collocation_Proxy_Broker.h"
#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#endif /* _MSC_VER */

#if defined (__BORLANDC__)
#pragma option push -w-rvl -w-rch -w-ccc -w-inl
#endif /* __BORLANDC__ */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_sh.cpp:87

class POA_Time;
typedef POA_Time *POA_Time_ptr;


class  POA_Time
  : public virtual PortableServer::ServantBase
{
protected:
  POA_Time (void);

public:
  // Useful for template programming.
  typedef ::Time _stub_type;
  typedef ::Time_ptr _stub_ptr_type;
  typedef ::Time_var _stub_var_type;
  
  POA_Time (const POA_Time& rhs);
  virtual ~POA_Time (void);
  
  virtual CORBA::Boolean _is_a (
      const char* logical_type_id
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  static void _is_a_skel (
      TAO_ServerRequest &req,
      void * servant_upcall,
      void * servant
      ACE_ENV_ARG_DECL
    );
  
  static void _non_existent_skel (
      TAO_ServerRequest &req,
      void * servant_upcall,
      void * servant
      ACE_ENV_ARG_DECL
    );
  
  static void _interface_skel (
      TAO_ServerRequest &req,
      void * servant_upcall,
      void * servant
      ACE_ENV_ARG_DECL
    );
  
  static void _component_skel (
      TAO_ServerRequest &req,
      void * servant_upcall,
      void * servant
      ACE_ENV_ARG_DECL
    );
  
  virtual void _dispatch (
      TAO_ServerRequest &req,
      void * servant_upcall
      ACE_ENV_ARG_DECL
    );
  
  ::Time *_this (
      ACE_ENV_SINGLE_ARG_DECL_WITH_DEFAULTS
    );
  
  virtual const char* _interface_repository_id (void) const;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual CORBA::Long current_time (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  static void current_time_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
      ACE_ENV_ARG_DECL
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual void shutdown (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  static void shutdown_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
      ACE_ENV_ARG_DECL
    );
};

// TAO_IDL - Generated from 
// be/be_codegen.cpp:976

#include "TimeS_T.h"

#if defined (__ACE_INLINE__)
#include "TimeS.inl"
#endif /* defined INLINE */

#if defined(_MSC_VER)
#pragma warning(pop)
#endif /* _MSC_VER */

#if defined (__BORLANDC__)
#pragma option pop
#endif /* __BORLANDC__ */

#include /**/ "ace/post.h"
#endif /* ifndef */

