// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:525

#ifndef _TAO_IDL_TIMES_T_H_
#define _TAO_IDL_TIMES_T_H_

#include /**/ "ace/pre.h"

#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#endif /* _MSC_VER */


// TAO_IDL - Generated from
// be/be_visitor_interface/tie_sh.cpp:87

// TIE class: Refer to CORBA v2.2, Section 20.34.4
template <class T>
class  POA_Time_tie : public POA_Time
{
public:
  POA_Time_tie (T &t);
  // the T& ctor
  POA_Time_tie (T &t, PortableServer::POA_ptr poa);
  // ctor taking a POA
  POA_Time_tie (T *tp, CORBA::Boolean release = 1);
  // ctor taking pointer and an ownership flag
  POA_Time_tie (
      T *tp,
      PortableServer::POA_ptr poa,
      CORBA::Boolean release = 1
    );
  // ctor with T*, ownership flag and a POA
  ~POA_Time_tie (void);
  // dtor
  
  // TIE specific functions
  T *_tied_object (void);
  // return the underlying object
  void _tied_object (T &obj);
  // set the underlying object
  void _tied_object (T *obj, CORBA::Boolean release = 1);
  // set the underlying object and the ownership flag
  CORBA::Boolean _is_owner (void);
  // do we own it
  void _is_owner (CORBA::Boolean b);
  // set the ownership
  
  // overridden ServantBase operations
  PortableServer::POA_ptr _default_POA (
      ACE_ENV_SINGLE_ARG_DECL_WITH_DEFAULTS
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/tie_sh.cpp:60
  
  CORBA::Long current_time (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/tie_sh.cpp:60
  
  void shutdown (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));

private:
  T *ptr_;
  PortableServer::POA_var poa_;
  CORBA::Boolean rel_;
  
  // copy and assignment are not allowed
  POA_Time_tie (const POA_Time_tie &);
  void operator= (const POA_Time_tie &);
};

// TAO_IDL - Generated from 
// be/be_codegen.cpp:1073

#if defined (__ACE_INLINE__)
#include "TimeS_T.inl"
#endif /* defined INLINE */

#if defined (ACE_TEMPLATES_REQUIRE_SOURCE)
#include "TimeS_T.cpp"
#endif /* defined REQUIRED SOURCE */

#if defined (ACE_TEMPLATES_REQUIRE_PRAGMA)
#pragma implementation ("TimeS_T.cpp")
#endif /* defined REQUIRED PRAGMA */

#if defined(_MSC_VER)
#pragma warning(pop)
#endif /* _MSC_VER */

#include /**/ "ace/post.h"
#endif /* ifndef */

