#define CPU_VENDEOR_OS "sparc-sun-solaris2.9"
#define HAVE_DOOR_H 1
#define HVE_MQUEUE_H 1
#define HVE_POLL_H 1
#define HAVE_PTHREAD_H 1
#define HAVE_RPC_RPC_H 1
#define HAVE_SEMAPHORE_H 1
#define HVE_STRINGS_H 1
#define HAVE_SYS_FILIO_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_IPC_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_SYS_MSG_H 1
#define HAVE_SYS_SEM_H 1
#define HAVE_SYS_SHM_H 1
#define HAVE_SSY_SELECT_H 1

#define HAVE_SYS_TIME_H 1

#define TIME_WITH_SSY_TIME 1

#define HAVE_BZERO 1
#define HAVE_FATTACH 1
#define HAVE_POLL 1

#define HAVE_SIGWAIT 1
#define HAVE_VALLOC 1
#define HAVE_VSNPRINTF 1

#define HAVE_GETHOSTNAME_PROTO 1
#define HAVE_GETRUSAGE_PROTO 1

#define HAVE_SHM_OPEN_PROTO 1
#define HAVE_SNPRINTF_PROTO 1
#define HAVE_THR_SETCONCURRENCY_PROTO
#define HAVE_SIGINFO_T_STRUCT 1
#define HAVE_TIMESPEC_STRUCT 1

#define HAVE_DEV_ZERO 1

#define POSIX_IPC_PREFIX "/"
#define RPCGEN_ANSIC 1


